import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import {NextUIProvider} from "@nextui-org/system";
import {ThemeProvider as NextThemesProvider} from "next-themes";
import {Container} from "../shared/Container";
import Dropdown from "../widgets/Dropdown";
import Footer from "../widgets/Footer/Footer";
import FooterPrivicy from "../widgets/Footer/FooterPrivicy";
import {ReactNode} from "react";
import {NextAuthProvider} from "./providers";
import GetSession from "../widgets/GetSession";
import Sidebar from "../widgets/Sidebar";


const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

type RootLayoutProps = {
    children: ReactNode;
};

const RootLayout = ({children}: RootLayoutProps) => {
    return (
        <html lang="en">
        <body className={inter.className}>
        <NextUIProvider>
            <NextAuthProvider>
                <NextThemesProvider attribute="class" defaultTheme={'light'}>
                    <Container>
                            <Sidebar />
                            {children}
                            <div className={'flex w-full pr-4 items-center sm:hidden fixed z-10 bottom-0'}>
                                <Dropdown/>
                            </div>
                            <div className={'h-20 md:h-32'}></div>
                    </Container>
                    <Footer/>
                    <FooterPrivicy/>
                </NextThemesProvider>
            </NextAuthProvider>
        </NextUIProvider>
        </body>
        </html>
    )
        ;
}
export default RootLayout;